-- Seed sample Michigan grants data for rural businesses
INSERT INTO grants (title, description, funding_amount_min, funding_amount_max, deadline, eligibility_criteria, industry_tags, business_size_tags, source) VALUES
('Michigan Small Business Growth Fund', 'Grants for small businesses expanding operations in rural Michigan', 5000, 50000, '2025-12-31', 'Operating 2+ years, located in rural county, revenue under $1M', 'Manufacturing,Agriculture,Retail,Services', 'Small,Medium', 'Michigan Economic Development Corporation'),
('Rural Agricultural Development Grant', 'Support for agricultural businesses and value-added operations', 10000, 75000, '2025-11-30', 'Agricultural operations, 51%+ rural location', 'Agriculture,Food Production,Agribusiness', 'Small,Medium', 'USDA Rural Development'),
('Women-Owned Business Support Program', 'Grants for women entrepreneurs in rural Michigan', 5000, 40000, '2025-10-15', 'Female majority ownership, located in Michigan', 'All Industries', 'Startup,Small,Medium', 'Michigan Women Business Council'),
('Rural Technology Infrastructure Grant', 'Support for broadband and tech infrastructure in underserved areas', 25000, 200000, '2025-09-30', 'Rural location, tech infrastructure project', 'Technology,Telecommunications', 'Small,Medium,Large', 'Federal Communications Commission'),
('Manufacturing Excellence Initiative', 'Grants for manufacturers implementing new technologies', 15000, 100000, '2025-11-15', 'Manufacturing operation, Michigan location', 'Manufacturing', 'Small,Medium,Large', 'Michigan Manufacturing Association'),
('Community Business Resilience Fund', 'Support for businesses impacted by economic challenges', 5000, 30000, '2025-12-15', 'Active business, Michigan location, 1+ employee', 'All Industries', 'Startup,Small,Medium', 'Michigan Department of Labor'),
('Tourism & Hospitality Development Grant', 'Support for tourism and hospitality businesses in rural areas', 8000, 60000, '2025-10-31', 'Tourism/hospitality focused, rural Michigan', 'Hospitality,Tourism,Recreation', 'Small,Medium', 'Michigan Tourism Bureau'),
('Clean Energy Business Transition Grant', 'Support for businesses transitioning to sustainable practices', 12000, 80000, '2025-09-15', 'Commitment to green practices, Michigan based', 'Energy,Manufacturing,Agriculture,Services', 'Small,Medium', 'Michigan Energy Office'),
('Veteran-Owned Business Grant Program', 'Grants specifically for veteran entrepreneurs', 5000, 45000, '2025-12-31', 'Owner is verified veteran', 'All Industries', 'Startup,Small,Medium', 'Michigan Veterans Affairs'),
('Small Farm Sustainability Grant', 'Support for sustainable farming practices and diversification', 3000, 25000, '2025-10-30', 'Farm operation under 500 acres, Michigan location', 'Agriculture,Agribusiness', 'Small', 'Michigan Farmers Bureau');
